[tool.poetry]
name = "docbridge-web"
version = "0.1.0"
description = ""
authors = ["Zijian Wu <zijian.wu14@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
astro = "^0.2.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
